#!/usr/bin/env bash

echo "Just a collection of random CPP stuff" > README.md
echo "" >> README.md
echo "[![Build Status](https://travis-ci.org/akhilnarang/CPP.svg?branch=master)](https://travis-ci.org/akhilnarang/CPP)" >> README.md
echo "" >> README.md
for f in $(ls *.cpp); do echo $f >> README.md; grep "^ \* " $f >> README.md; echo >> README.md; done
git add -A
git commit -asm "Automated README update on $(date +%x)"
git push origin master -u
