#!/usr/bin/env bash

echo "Just a collection of random C stuff" > README.md
echo "" >> README.md
echo "[![Build Status](https://travis-ci.org/akhilnarang/cstuff.svg?branch=master)](https://travis-ci.org/akhilnarang/cstuff)" >> README.md
echo "" >> README.md
for f in $(ls *.c); do echo $f >> README.md; grep "^ \* " $f >> README.md; echo >> README.md; done
git commit -asm "Automated README update on $(date +%x)"
git push origin master -u
