#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR_Sensor,      sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servoBox,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    lift_hook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Angular_Lift,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define button1   0x01
#define button2   0x02
#define button3   0x04
#define button4   0x08
#define button5   0x10
#define button6   0x20
#define button7   0x40
#define button8   0x80
#define button9  0x100
#define button10 0x200

#include "JoystickDriver.c"

#define maxPower 95

void InitializeServos()
{
  	servoTarget[servoBox] = 127.5;
    	servo[lift_hook]=195;
}

void lift(int speed)
{
	motor[motorLift] = speed;
}

void Move(int speed)
{
	motor[motorLeft] = speed;
	motor[motorRight] = speed;
}

void Turn(int speed)
{
	motor[motorLeft] = speed;
	motor[motorRight] = -speed;
}

void StopMotors()
{
	motor[motorLift] = 0;
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
		motor[Flag]=0;

}

void MoveRobot(TJoystick joystick)
{

	if (joystick.joy1_y1 < -15 || joystick.joy1_y1 > 15)
	{
		float value =(float)joystick.joy1_y1/128.0;
		int scaledValue = value * maxPower;
		Move(scaledValue);
	}

	else if (joystick.joy1_x1 < -15 || joystick.joy1_x1 > 15)
	{
		float value =(float)joystick.joy1_x1/128.0;
		int scaledValue = value * maxPower;
		Turn(scaledValue);
	}

	else if(joystick.joy2_y1 < -10 && ServoValue[servoBox] <= 230)
	{
		servo[servoBox] += 15;
	}

	else if(joystick.joy2_y1 > 10 && ServoValue[servoBox] >= 25)
	{
		servo[servoBox] -= 15;
	}

	else if (joystick.joy2_y2 < -15 || joystick.joy2_y2 > 15)
	{
		float value =(float)joystick.joy2_y2/128.0;
		int scaledValue = value * maxPower;

		lift(scaledValue);
	}

	 else if(joystick.joy2_Buttons & button1)
		{
				motor[Flag]=100;
		}



			 else if(joystick.joy2_Buttons & button5 && ServoValue[lift_hook]<=230)
			   {
			   servo[lift_hook] +=15;

			   }
			   else if(joystick.joy2_Buttons & button7 && ServoValue[lift_hook]>=25)
			   {
			   servo[lift_hook] -=15;

			   }
		 else
  {
		StopMotors();
  }
}


task main()
{
	InitializeServos();


	while(true)
	{
		getJoystickSettings(joystick);
		MoveRobot(joystick);
		wait1Msec(200);
  }
}
