/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lists;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author Akhil Narang <akhilnarang.1999@gmail.com>
 */
public class listForm extends javax.swing.JFrame {
    
    
    DefaultListModel dlm;
    /**
     * Creates new form listForm
     */
    public listForm() {
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOne = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaOne = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();
        toggleListButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        colorList = new javax.swing.JList<>();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOne.setModel(new javax.swing.AbstractListModel<String>()
            {
                String[] strings = { "Pizza", "Pasta", "WadaPav", "Chiwda", "Chat" };
                public int getSize()
                {
                    return strings.length;
                }
                public String getElementAt(int i)
                {
                    return strings[i];
                }
            });
            listOne.setSelectionMode(0);
            listOne.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    onListValueChange(evt);
                }
            });
            jScrollPane1.setViewportView(listOne);

            textAreaOne.setEditable(false);
            textAreaOne.setColumns(20);
            textAreaOne.setRows(5);
            jScrollPane2.setViewportView(textAreaOne);

            clearButton.setBackground(new java.awt.Color(100, 100, 255));
            clearButton.setFont(new java.awt.Font("Ubuntu Condensed", 0, 12)); // NOI18N
            clearButton.setText("Clear");
            clearButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    clearButtonActionPerformed(evt);
                }
            });

            toggleListButton.setText("ThugLife");
            toggleListButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    toggleListButtonActionPerformed(evt);
                }
            });

            colorList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Red", "Blue", "Cyan", "Green", "Yellow", "White", "Magenta", "Default" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            colorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    colorListValueChanged(evt);
                }
            });
            jScrollPane3.setViewportView(colorList);

            deleteButton.setText("Delete Selected Item");
            deleteButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    deleteButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(deleteButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toggleListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(188, 188, 188))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(clearButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(toggleListButton)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(deleteButton)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            toggleListButton.setBackground(new java.awt.Color(100, 100, 255));

            toggleListButton.setFont(new java.awt.Font("Ubuntu Condensed", 0, 12)); // NOI18N

            pack();
        }// </editor-fold>//GEN-END:initComponents

    void postInit() {
        dlm = new DefaultListModel();
        listOne.setModel(dlm);
    }
    private void onListValueChange(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_onListValueChange
        String food=listOne.getSelectedValue();
        if (food != null)
            textAreaOne.setText("Hmm, nice choice with the "+food);
        
    }//GEN-LAST:event_onListValueChange

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        listOne.clearSelection();
        textAreaOne.setText("Cleared :P");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void toggleListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleListButtonActionPerformed
        boolean listIsEnabled=listOne.isEnabled();
        listOne.setEnabled(!listIsEnabled);
        clearButton.setEnabled(!listIsEnabled);
        if (listIsEnabled)
        {
            toggleListButton.setText("Enable List And Clear Button");
            textAreaOne.setText("The List And The Clear Button have been disabled!");
        }
        else
        {
            toggleListButton.setText("Disable List And Clear Button");
            textAreaOne.setText("The List And The Clear Button have been re-enabled");
        }
    }//GEN-LAST:event_toggleListButtonActionPerformed

    private void colorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_colorListValueChanged
        int n=colorList.getSelectedIndex();
        Color ta=new JTextArea().getBackground();
        Color l=new JList().getBackground();
        Color c=check(n);
        toggleListButton.setBackground(c);
        clearButton.setBackground(c);
        if (n!=7)
        {
            textAreaOne.setBackground(c);
            listOne.setBackground(c);
            colorList.setBackground(c);
        }
        else
        {
            textAreaOne.setBackground(ta);
            listOne.setBackground(l);
            colorList.setBackground(l);
        }      
        
        
    }//GEN-LAST:event_colorListValueChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int n = listOne.getSelectedIndex();
        dlm.remove(n);
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    public Color check(int i)
     {
         Color c=new JButton().getBackground();
         switch (i)
         {
             case 0:c=Color.RED;break;          
             case 1:c=Color.BLUE;break;
             case 2:c=Color.CYAN;break;
             case 3:c=Color.GREEN;break;
             case 4:c=Color.YELLOW;break;
             case 5:c=Color.WHITE;break;
             case 6:c=Color.MAGENTA;break;
         }
         return c;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JList<String> colorList;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listOne;
    javax.swing.JTextArea textAreaOne;
    private javax.swing.JButton toggleListButton;
    // End of variables declaration//GEN-END:variables
}
